# Generated by Django 5.2.4 on 2025-07-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'product'], name='accounts_ca_user_id_3b79ef_idx'),
        ),
    ]
