# Generated by Django 5.2.4 on 2025-08-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('seller', 'Commerçant'), ('delivery', 'Livreur'), ('admin', 'Admin'), ('manager', 'Gestionnaire')], default='client', max_length=15),
        ),
    ]
