# Generated by Django 5.2.4 on 2025-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_address',
            field=models.CharField(default='Adresse par défaut', max_length=255),
        ),
    ]
